services:
  - type: web
    name: faacan-telegram-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    env: python
    region: frankfurt
    plan: free
    branch: main
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "7411394370"
      - key: TELEGRAM_CHAT_ID
        value: "-1002663732392"
