services:
  - type: web
    name: faacan-telegram-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    env: python
    region: frankfurt
    plan: free
    branch: main
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "8100909334:AAHm7_bFkU9lZwrL7P7KGb6jXBC04fH7uHo"
      - key: TELEGRAM_CHAT_ID
        value: "-1002128827347"
